# Generated by Django 5.2 on 2025-05-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, default="", max_length=300)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SchoolParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_id", models.CharField(max_length=200)),
                ("acceptance_rate", models.FloatField()),
                ("tuition", models.IntegerField()),
            ],
        ),
    ]
