# Generated by Django 5.2 on 2025-05-16 01:57

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nationality",
            field=django_countries.fields.CountryField(
                blank=True, help_text="Country of nationality", max_length=2, null=True
            ),
        ),
    ]
