# Generated by Django 5.2 on 2025-05-09 06:31

import backend.models
import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_frontenduser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sat_reading",
                    models.PositiveSmallIntegerField(
                        help_text="SAT Reading score, 200–800 in 10‑point increments",
                        validators=[
                            django.core.validators.MinValueValidator(200),
                            django.core.validators.MaxValueValidator(800),
                            backend.models.StepValidator(10),
                        ],
                    ),
                ),
                (
                    "sat_math",
                    models.PositiveSmallIntegerField(
                        help_text="SAT Math score, 200–800 in 10‑point increments",
                        validators=[
                            django.core.validators.MinValueValidator(200),
                            django.core.validators.MaxValueValidator(800),
                            backend.models.StepValidator(10),
                        ],
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="GPA on a 0.00–4.00 scale in 0.05 increments",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(4.0),
                            backend.models.StepValidator(0.05),
                        ],
                    ),
                ),
                (
                    "intended_major",
                    models.CharField(
                        choices=[
                            ("ENG", "Engineering"),
                            ("MTH", "Mathematics"),
                            ("PHY", "Physics"),
                            ("CHM", "Chemistry"),
                            ("BIO", "Biology"),
                            ("ENGG", "English"),
                            ("HIS", "History"),
                        ],
                        default="ENG",
                        help_text="Intended college major",
                        max_length=4,
                    ),
                ),
                (
                    "recommendation_strength",
                    models.PositiveSmallIntegerField(
                        help_text="How strong the recommendation is (1–4)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "nationality",
                    django_countries.fields.CountryField(
                        help_text="Country of nationality", max_length=2
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other / Prefer not to say"),
                        ],
                        default="O",
                        help_text="Gender identity",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="frontenduser",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baseuser",
                to="backend.userprofile",
            ),
        ),
    ]
